on:
  push:
    branches:
      - main
name: Deploy website on push

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3

    - name: Use Node.js 20
      uses: actions/checkout@v2
      with:
        node-version: '20'
    
    - name: Build Project
      run: |
        export SESSION_SECRET="dkau82838hfdklfakld2039"
        export DATABASE_URL="postgres://iflexic1:o$q9sixT};6l@iflexico.com:7822/iflexic1_bookclub_db"
        npm install
        npm start
      
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server:   ${{ secrets.GIT_CPANEL_BOOKCLUB_SERVER }}
        username: ${{ secrets.GIT_CPANEL_BOOKCLUB_USER }}
        password: ${{ secrets.GIT_CPANEL_BOOKCLUB_PWD }}
        protocol: ${{ secrets.GIT_CPANEL_BOOKCLUB_PROTOCOL }}
        # local-dir: ./dist/
